import React,{useEffect,useState} from "react";
import {ArrowUpRight,CheckCircle2,Clock3,Flame,Sparkles,Target,TrendingUp} from "lucide-react";
import {AreaChart,Area,ResponsiveContainer,Tooltip,XAxis} from "recharts";
import Layout from "../components/Layout"; import Metric from "../components/Metric"; import Progress from "../components/Progress"; import RecommendationCard from "../components/RecommendationCard"; import api from "../services/api";

const fallback={progress:{overall:72,completed:8,streak:6,hours:31},weekly:[{day:"Mon",hours:1.8},{day:"Tue",hours:2.7},{day:"Wed",hours:1.5},{day:"Thu",hours:3.4},{day:"Fri",hours:2.8},{day:"Sat",hours:4.1},{day:"Sun",hours:2.9}],recommendations:[
{title:"Data Science",match:94,description:"Strong alignment with your analytical interests and Python foundation.",skills:["Python","Statistics","ML","SQL"],reason:"Best current fit"},
{title:"ML Engineer",match:88,description:"A strong technical route if you want to build intelligent systems.",skills:["Python","ML","APIs","Cloud"],reason:"High growth path"},
{title:"Data Analyst",match:84,description:"A practical path to convert your SQL and analytical strengths into impact.",skills:["SQL","Excel","BI","Python"],reason:"Fast skill conversion"}]};
export default function Dashboard(){const [d,setD]=useState(fallback);useEffect(()=>{api.get("/analytics/overview").then(r=>setD(r.data)).catch(()=>{})},[]);
return <Layout title="Good evening, Aishwarya 👋" subtitle="Here’s your personalized snapshot for today.">
<section className="hero"><div><span><Sparkles size={13}/> AI INSIGHT OF THE DAY</span><h2>You’re closer to your target than you think.</h2><p>Your strongest advantage is the combination of Python + analytical thinking. Focus next on statistics and model deployment.</p><a href="/skills">View my skill roadmap <ArrowUpRight size={15}/></a></div><div className="hero-ring"><b>{d.progress.overall}%</b><small>readiness</small></div></section>
<div className="metrics"><Metric label="Career readiness" value={`${d.progress.overall}%`} change="+8% this month" icon={TrendingUp}/><Metric label="Learning streak" value={`${d.progress.streak} days`} change="Keep it going!" icon={Flame}/><Metric label="Courses completed" value={d.progress.completed} change="+2 this month" icon={CheckCircle2}/><Metric label="Learning hours" value={`${d.progress.hours}h`} change="This month" icon={Clock3}/></div>
<div className="two"><section className="panel"><div className="panel-head"><div><span className="eyebrow">ACTIVITY</span><h3>Learning momentum</h3></div><label className="soft">Last 7 days</label></div><ResponsiveContainer width="100%" height={235}><AreaChart data={d.weekly}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopOpacity=".3"/><stop offset="100%" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="day" axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="hours" strokeWidth={3} fill="url(#g)"/></AreaChart></ResponsiveContainer></section>
<section className="panel"><div className="panel-head"><div><span className="eyebrow">CURRENT PATH</span><h3>Data Science roadmap</h3></div><Target size={18}/></div><div className="road"><div className="road-row done"><b>01</b><div><strong>Python Foundations</strong><small>Completed</small></div><CheckCircle2 size={16}/></div><hr/><div className="road-row active"><b>02</b><div><strong>Statistics & Probability</strong><small>In progress • 64%</small><Progress value={64}/></div><label>NOW</label></div><hr/><div className="road-row"><b>03</b><div><strong>Machine Learning</strong><small>Up next</small></div></div></div></section></div>
<div className="section-head"><div><span className="eyebrow">PERSONALIZED FOR YOU</span><h2>Top career matches</h2></div><a href="/recommendations">See all <ArrowUpRight size={14}/></a></div><div className="rec-grid">{d.recommendations.map(x=><RecommendationCard key={x.title} item={x}/>)}</div>
</Layout>}
